### ISSUE TITLE
Check in request or response

### ISSUE THREAD

**Issue by Techbrunch** [PortSwigger/BChecks#138]
We have created a simple BCheck to flag response with `Content-Type: text/event-stream`:

```
metadata:
    language: v1-beta
    name: "Event-stream detection"
    description: "Checks for event-stream (passive)"
    tags: "passive"

given response then
	if "text/event-stream" in {latest.response.headers} then
	    report issue:
	        severity: info
	        confidence: certain
	        detail: "The Content-Type: Event-stream is set in the response."
	end if
```

We would like to also check the request for `Accept: text/event-stream` in the same BCheck but that does not appear to be possible.

Basically what we would like is `given request or response contains text/event-stream then report issue`.
