### ISSUE TITLE
[BUG] Missing request when using two `send request called check` with run for each

### ISSUE THREAD

**Issue by j3ssie** [PortSwigger/BChecks#170]
I was testing the Bcheck scan below that I want to test the .svn file.

```yaml
metadata:
    language: v1-beta
    name: "SVN Configuration Check"
    description: "Tests for exposed svn config in current path and at the root directory of site"
    author: "j3ssie"
    tags: "exposure", "svn", "config", "file"

run for each:
    potential_path = ".svn/entries", ".svn/text", ".svn/all-wcprops", "CVS/Entries"

given request then
    # replace the potential path with the last path
    send request called check:
        method: "GET"
        replacing path: `{regex_replace({regex_replace({base.request.url}, "^.*?\/.*?\/.*?\/", "/")}, "([^/]+)$", "")}{potential_path}`

    # replace the potential path with entire URI
    send request called check:
        method: "GET"
        replacing path: `{regex_replace({base.request.url}, "^.*", "")}/{potential_path}`

    if {check.response.status_code} is "200" and
        "END" in {check.response.body} and
        "svn:" in {check.response.body} then
        report issue:
            severity: low
            confidence: tentative
            detail: `SVN configuration found at {potential_path}.`
    end if

    if {check.response.status_code} is "200" and
        "dir" in {check.response.body} and
        "<entry:" in {check.response.body} then
        report issue:
            severity: low
            confidence: tentative
            detail: `SVN configuration found at {potential_path}.`
    end if

```

Let's say my original URL/request that is sent from Burp to BCheck is `https://example.com/api/settings/public`

## Expected Behavior

I expected the BCheck will send all of the requests below but it only sends 2 requests as I show in the `Actual Behavior`

```
https://example.com/.svn/entries
https://example.com/.svn/text
https://example.com/.svn/all-wcprops
https://example.com/CVS/Entries

https://example.com/api/settings/.svn/entries
https://example.com/api/settings/.svn/text
https://example.com/api/settings/.svn/all-wcprops
https://example.com/api/settings/CVS/Entries

```

## Actual Behavior
It only sends 2 requests below 

```
https://example.com/.svn/entries
https://example.com/api/settings/.svn/entries
```

I'm also trying to use 2 sections of `given request then` but looks like BCheck didn't allow that.

### Environment details

  - Burp version: v2023.12.1.3
  - BCheck language version: v1-beta
  - Operating System: MacOS Apple Silicon
